package net.noliaware.yumi_contributor.commun

const val BASE_URL = "https://api.noliaware.net/yumi/contributor/"
const val INIT = "init"
const val CONNECT = "connect"
const val GET_MANAGED_ACCOUNT_LIST = "getUserList"
const val SELECT_USER = "selectUser"
const val GET_AVAILABLE_VOUCHER_LIST_BY_CATEGORY = "getUserAvailableVoucherListByCategory"
const val GET_VOUCHER = "getUserVoucher"
const val GET_VOUCHER_STATUS = "getUserVoucherStatus"
const val USE_VOUCHER = "useUserVoucher"
const val GET_ACCOUNT = "getAccount"
const val GET_BACK_OFFICE_SIGN_IN_CODE = "getBackOfficeSignInCode"
const val GET_DATA_PER_CATEGORY = "getUserDataPerCategory"
const val GET_USED_VOUCHER_LIST_BY_CATEGORY = "getUserUsedVoucherListByCategory"
const val GET_ALERT_LIST = "getAlertList"
const val GET_INBOX_MESSAGE_LIST = "getInboxMessageList"
const val GET_INBOX_MESSAGE = "getInboxMessage"
const val GET_OUTBOX_MESSAGE_LIST = "getOutboxMessageList"
const val GET_OUTBOX_MESSAGE = "getOutboxMessage"
const val SEND_MESSAGE = "sendMessage"
const val DELETE_INBOX_MESSAGE = "delInboxMessage"
const val DELETE_OUTBOX_MESSAGE = "delOutboxMessage"

const val LOGIN = "login"
const val PASSWORD = "password"
const val APP_VERSION = "appVersion"
const val DEVICE_ID = "deviceId"
const val DEVICE_TYPE = "deviceType"
const val DEVICE_OS = "deviceOS"
const val DEVICE_UUID = "deviceUUID"
const val DEVICE_LABEL = "deviceLabel"
const val SESSION_ID = "sessionId"
const val SESSION_TOKEN = "sessionToken"
const val TIMESTAMP = "timestamp"
const val SALT_STRING = "saltString"
const val TOKEN = "token"
const val KEYBOARD = "keyboard"
const val ENCRYPTION_VECTOR = "encryption_vector"
const val SELECTED_USER = "selectedUser"
const val VOUCHER_ID = "voucherId"
const val VOUCHER_CODE_DATA = "voucherCodeData"
const val LIMIT = "limit"
const val LIST_PAGE_SIZE = 20
const val OFFSET = "offset"
const val MESSAGE_ID = "messageId"
const val MESSAGE_PRIORITY = "messagePriority"
const val MESSAGE_SUBJECT_ID = "messageSubjectId"
const val MESSAGE_SUBJECT_LABEL = "messageSubjectLabel"
const val MESSAGE_BODY = "messageBody"
const val MESSAGE = "message"
const val MESSAGES = "messages"
const val ALERTS = "alerts"
const val TIMESTAMP_OFFSET = "timestampOffset"

const val ACCOUNT_DATA = "account_data"
const val MANAGED_ACCOUNT = "managed_account"
const val CATEGORIES_DATA = "categories_data"
const val MESSAGE_SUBJECTS_DATA = "message_subjects_data"
const val CATEGORY_ID = "categoryId"
const val CATEGORY_LABEL = "categoryLabel"

const val MESSAGE_INBOX_DAT = "message_inbox_dat"
const val MESSAGE_OUTBOX_DAT = "message_outbox_dat"

const val DATA_SHOULD_REFRESH = "dataShouldRefresh"
const val VOUCHER_VALIDATED = "voucherValidated"
const val SELECTED_MESSAGE_INDEX = "selectedMessageIndex"

//FRAGMENT TAGS
const val ACCOUNTS_LIST_FRAGMENT_TAG = "accounts_list_fragment"
const val VOUCHERS_LIST_FRAGMENT_TAG = "vouchers_list_fragment"
const val BO_SIGN_IN_FRAGMENT_TAG = "bo_sign_in_fragment"
const val USED_VOUCHERS_LIST_FRAGMENT_TAG = "used_vouchers_list_fragment"
const val VOUCHER_DETAILS_FRAGMENT_TAG = "voucher_details_fragment"
const val QR_CODE_FRAGMENT_TAG = "qr_code_fragment"
const val READ_MESSAGE_FRAGMENT_TAG = "read_message_fragment"
const val SEND_MESSAGES_FRAGMENT_TAG = "send_messages_fragment"

const val GOLDEN_RATIO = 1.6180339887