package net.noliaware.yumi_contributor.feature_account.domain.model

data class Voucher(
    val voucherId: String,
    val voucherNumber: String,
    val voucherCode: String?,
    val voucherStatus: VoucherStatus?,
    val voucherStartDate: String?,
    val voucherExpiryDate: String?,
    val voucherUseDate: String?,
    val voucherUseTime: String?,
    val voucherRetrievalMode: VoucherRetrievalMode?,
    val voucherDeliveryStatus: VoucherDeliveryStatus?,
    val productLabel: String?,
    val voucherOngoingRequestCount: Int,
    val productDescription: String?,
    val productWebpage: String?,
    val retailerType: String?,
    val retailerLabel: String?,
    val retailerAddress: String?,
    val retailerAddressComplement: String?,
    val retailerPostcode: String?,
    val retailerCity: String?,
    val retailerCountry: String?,
    val retailerAddressLatitude: String?,
    val retailerAddressLongitude: String?,
    val retailerPhoneNumber: String?,
    val retailerCellPhoneNumber: String?,
    val retailerEmail: String?,
    val retailerWebsite: String?,
    val partnerInfoText: String?,
    val partnerInfoURL: String?
)